version: '2'

services:
  reverse-proxy:
    image: reverse-proxy:latest
    build: 
      dockerfile: Dockerfile-reverse-proxy
      context: .
    ports:
      - "80:80"
      - "443:443"
  
  web:
    image: web:latest
    build:
      dockerfile: Dockerfile
      context: LIMS-web-client
    ports:
      - "3000:3000"

    depends_on:
      - api

  api:
    image: api:latest
    build:
      dockerfile: Dockerfile-api
      context: LIMS-api-server
    ports:
      - "8080:8080"
    depends_on:
      - db

  batch:
    image: batch:latest
    build:
      dockerfile: Dockerfile-batch
      context: LIMS-api-server
    depends_on:
      - api
      - db

  db:
    image: postgres:16.3-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "D3mabc^kahFg0a9)35^42vasfG"
    volumes:
      - ~/volume/pgdata:/var/lib/postgresql/data

  storage:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: "aRKK(!)_AAL4paoDAKSFN381"
    volumes:
      - ~/volume/minio/data:/data
    command: server /data --console-address ":9001"
