version: '2'

services:
  reverse:
    image: reverse:latest
    build: 
      dockerfile: Dockerfile-reverse
      context: .
    ports:
      - "80:80"
      - "443:443"

  
  web:
    image: web:latest
    build:
      dockerfile: Dockerfile-web
      context: ~/
    ports:
      - "3000:3000"