FROM nginx:1.19.0

WORKDIR /usr/share/nginx/html
RUN rm -rf ./*

COPY nginx.reverse.conf /etc/nginx/conf.d/default.conf
COPY keys/nginx-selfsigned.crt /etc/ssl/certs/nginx-selfsigned.crt
COPY keys/nginx-dhparam.pem /etc/ssl/certs/nginx-dhparam.pem
COPY keys/nginx-selfsigned.key /etc/ssl/private/nginx-selfsigned.key

ENTRYPOINT ["nginx", "-g", "daemon off;"]